#ifndef PLATFORM_CONFIG_H
#define PLATFORM_CONFIG_H

#define STACK_SIZE (4096)
#define STACK_TOP  (RAM_BASE + RAM_SIZE)
#define STACK_BASE (STACK_TOP - STACK_SIZE)

#endif //PLATFORM_CONFIG_H
